USE [EXPRESS-CINEMA]
GO

/****** Object:  Table [dbo].[CINEMA_ORDERS]    Script Date: 16/09/2019 08:27:38 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CINEMA_ORDERS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[EMPNIT] [varchar](20) NULL,
	[CODDOC] [varchar](5) NULL,
	[CORRELATIVO] [numeric](18, 0) NULL,
	[FECHA] [date] NULL,
	[PELICULA] [varchar](255) NULL,
	[NOSALA] [int] NULL,
	[NOASIENTO] [int] NULL,
	[NOFILA] [int] NULL,
	[HORAINICIO] [varchar](2) NULL,
	[MINUTOINICIO] [varchar](2) NULL,
	[HORAFIN] [varchar](2) NULL,
	[MINUTOFIN] [varchar](2) NULL,
 CONSTRAINT [PK_CINEMA_ORDERS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

