USE [EXPRESS-CINEMA]
GO

/****** Object:  Table [dbo].[CINEMA_CARTELERA]    Script Date: 12/07/2019 00:08:17 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CINEMA_CARTELERA](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[FECHA] [date] NULL,
	[ANIO] [int] NULL,
	[MES] [int] NULL,
	[DIA] [int] NULL,
	[TITULO] [varchar](250) NULL,
	[FECHAINICIO] [date] NULL,
	[FECHAFIN] [date] NULL,
	[IMG] [varchar](250) NULL,
	[CODSALA] [int] NULL,
	[HORA] [varchar](2) NULL,
	[MINUTO] [varchar](2) NULL,
	[HORAFIN] [varchar](2) NULL,
	[MINUTOFIN] [varchar](2) NULL,
	[ANIOF] [int] NULL,
	[MESF] [int] NULL,
	[DIAF] [int] NULL,
	[ACTIVA] [varchar](2) NULL,
 CONSTRAINT [PK_CARTELERA] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

